# Generated by Django 2.0.2 on 2019-05-24 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameModule', models.CharField(max_length=200, verbose_name='Nombre del módulo')),
                ('nameAdmin', models.CharField(max_length=200, verbose_name='Nombre completo del admin')),
                ('eMail', models.CharField(max_length=200, verbose_name='E-mail del admin')),
                ('cel', models.CharField(max_length=10, verbose_name='Tel del admin')),
                ('descModule', models.TextField(blank=True, verbose_name='Descripcion del módulo')),
                ('image', models.ImageField(upload_to='servicios', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Administrador del módulo')),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
                'ordering': ['-created'],
            },
        ),
    ]
