-- MySQL Script generated by MySQL Workbench
-- Wed May 22 16:11:24 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `tipo` INT NOT NULL,
  `correo` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `Nombre` VARCHAR(70) NULL,
  `apPaterno` VARCHAR(70) NULL,
  `apMaterno` VARCHAR(70) NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Alumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Alumno` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Alumno` (
  `idAlumno` INT NOT NULL,
  `Boleta` INT NULL,
  PRIMARY KEY (`idAlumno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Administrador` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Administrador` (
  `idAdministrador` INT NOT NULL,
  `tel` VARCHAR(45) NULL,
  PRIMARY KEY (`idAdministrador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Servicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Servicio` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Servicio` (
  `idServicio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `Ubicación` VARCHAR(100) NULL,
  `idAdministrador` INT NULL,
  `Hora_inicio` TIME NULL,
  `Hora_final` TIME NULL,
  `imagen` VARCHAR(100) NULL,
  PRIMARY KEY (`idServicio`))
ENGINE = InnoDB;

CREATE INDEX `idAdministrador_idx` ON `mydb`.`Servicio` (`idAdministrador` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Publicación`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Publicación` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Publicación` (
  `idPublicación` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `contenido` VARCHAR(300) NULL,
  `idUsuario` INT NULL,
  `idServicio` INT NULL,
  `imagen` VARCHAR(100) NULL,
  PRIMARY KEY (`idPublicación`))
ENGINE = InnoDB;

CREATE INDEX `idUsuario_idx` ON `mydb`.`Publicación` (`idUsuario` ASC);

CREATE INDEX `idServicio_idx` ON `mydb`.`Publicación` (`idServicio` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Comentario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Comentario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Comentario` (
  `idComentario` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `contenido` VARCHAR(300) NULL,
  `idUsuario` INT NULL,
  `idPublicación` INT NULL,
  PRIMARY KEY (`idComentario`))
ENGINE = InnoDB;

CREATE INDEX `idPublicacion_idx` ON `mydb`.`Comentario` (`idUsuario` ASC, `idPublicación` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Club`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Club` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Club` (
  `idClub` INT NOT NULL,
  `Hora_Inicio` TIME NULL,
  `Hora_Final` TIME NULL,
  PRIMARY KEY (`idClub`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dia_Club`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Dia_Club` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Dia_Club` (
  `idClub` INT NOT NULL,
  `día` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idClub`, `día`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Evento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Evento` (
  `idEvento` INT NOT NULL AUTO_INCREMENT,
  `fecha_incio` DATETIME NULL,
  `fecha_final` DATETIME NULL,
  `Encargardo` VARCHAR(100) NULL,
  `Descripción` VARCHAR(300) NULL,
  `idServicion` INT NULL,
  `nombre` VARCHAR(100) NULL,
  `imagen` VARCHAR(100) NULL,
  PRIMARY KEY (`idEvento`))
ENGINE = InnoDB;

CREATE INDEX `idServicio_idx` ON `mydb`.`Evento` (`idServicion` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Dia_Servicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Dia_Servicio` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Dia_Servicio` (
  `idServicio` INT NOT NULL,
  `Dia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idServicio`, `Dia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Notificación`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Notificación` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Notificación` (
  `idNotificación` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL,
  `contenido` VARCHAR(300) NULL,
  `idServicio` INT NULL,
  PRIMARY KEY (`idNotificación`))
ENGINE = InnoDB;

CREATE INDEX `idServicio_idx` ON `mydb`.`Notificación` (`idServicio` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Alumno_Not`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Alumno_Not` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Alumno_Not` (
  `idAlumno` INT NOT NULL,
  `idNotificacion` INT NOT NULL,
  PRIMARY KEY (`idAlumno`, `idNotificacion`))
ENGINE = InnoDB;

CREATE INDEX `idNotificacion_idx` ON `mydb`.`Alumno_Not` (`idNotificacion` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;